name: build
on:
  workflow_dispatch:
  schedule:
    - cron: '5 6 */60 * *'
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: git p7zip unzip
    - name: Download winget
      run: wget -nv https://github.com/microsoft/winget-cli/releases/latest/download/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
    - name: Install AppxPackages
      shell: powershell
      run: |
        nuget install Microsoft.UI.Xaml
        Add-AppxPackage Microsoft.UI.Xaml.*\tools\appx\x86\Release\Microsoft.UI.Xaml.*.appx
        Add-AppxPackage Microsoft.UI.Xaml.*\tools\appx\x64\Release\Microsoft.UI.Xaml.*.appx
        Add-AppxPackage "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs.Desktop\14.0\Appx\Retail\x64\Microsoft.VCLibs.x64.14.00.Desktop.appx"
        Add-AppxProvisionedPackage -Online -PackagePath Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -LicensePath License1.xml
    - name: Reinstall Visual Studio and WindowsSDK
      run: ./reinstall.sh
    - name: Package Visual Studio
      run: ./package.sh
    - name: Release
      if: env.version
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.version }}
        fail_on_unmatched_files: false
        files: |
          MSVS_HASH
          VisualStudio-*.7z*
          VisualStudio-*.zip*
          ${{ env.origin_file }}
    - name: Setup tmate ssh session
      if: failure()
      uses: mxschmitt/action-tmate@v3
